# Site settings
title: Nicholas W. Watson
email: nicholas.watson@nickonsoftware.com
disqus_shortname: nicholaswatson
description: > # this means to ignore newlines until "baseurl:"
  Husband, Father, God fearing VP of Technology at Gleason Technology.
  Thoughts on technology, software and management.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

gems:
  - jekyll-gist
  - jekyll-paginate

owner:
  name:           Nicholas W. Watson
  email:          nwwatson@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Husband, Father, God fearing VP of Technology at Gleason Technology
  # Social networking links used in footer. Update and remove as you like.
  twitter:        nwwatson
  github:         nwwatson

# Analytics and webmaster tools stuff goes here
google_analytics: UA-57714341-1

excerpt_separator: <!--more-->

paginate: 5

# Build settings
markdown: kramdown

exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
